"""Runtime engine: executes the org charts generated by bootstrap.

M1 scope: a provider-agnostic agent loop over a Role + task, with SQLite-backed
durable state, a real tool framework (files/web + stubs), and approval gating.
"""

from .agent import Action, AgentLimitError, AgentOutcome, build_system_prompt, parse_action, run_agent
from .ambition import Proposal, propose_actions, run_ambition_loop
from .state import Store
from .tools import ApprovalFn, Tool, ToolFunc, tools_for_role
from .orchestrator import run_job

__all__ = [
    "Action",
    "AgentLimitError",
    "AgentOutcome",
    "build_system_prompt",
    "parse_action",
    "run_agent",
    "Proposal",
    "propose_actions",
    "run_ambition_loop",
    "Store",
    "Tool",
    "ToolFunc",
    "ApprovalFn",
    "tools_for_role",
    "run_job",
]
