"""Text templates for generated org artifacts (SOP runbooks + goals).

These keep the generation output human- and agent-readable Markdown. They are
plain-format functions (no Jinja dependency) so the factory has zero template
runtime dependencies.
"""

from __future__ import annotations

from ..config import Org, Role


def render_sop(org: Org, role: Role, workers: list[str]) -> str:
    """Return a Markdown SOP runbook for a single role."""
    lines = [
        f"# SOP — {role.title}",
        "",
        f"**Role:** `{role.id}`   **Reports to:** `{role.reports_to or 'org lead'}`",
        "",
        f"## Charter",
        role.charter.strip(),
        "",
        f"## Proactivity level: {role.proactivity_level}",
        _proactivity_desc(role.proactivity_level),
        "",
        f"## Model tier: `{role.model_tier.value}`",
        "",
        f"## Approval policy: `{role.approval_policy.value}`",
        "",
        "## Working SOP",
        "1. Operate toward the org north star and this quarter's goals (see `goals/current.md`).",
        "2. Use only granted tools; treat `write` grants as requiring care, and any "
        "``requires_approval`` grant as blocked until a human approves.",
        "3. When a task is ambiguous, form a small plan and state assumptions before acting.",
        "4. If you cannot complete a task safely, stop and escalate rather than guess.",
        "5. For proactive work, prefer high-value, low-risk actions; report tradeoffs and "
        "rollback steps for anything beyond routine.",
        "",
        "## Granted tools",
    ]

    if role.tool_grants:
        for g in role.tool_grants:
            marker = " (requires approval)" if g.requires_approval else ""
            lines.append(f"- `{g.tool}` — {g.access.value}{marker}")
    else:
        lines.append("- (none yet — connect tools in the runtime)")

    if workers:
        lines += ["", "## Reports to this role", ""]
        lines += [f"- `{w}`" for w in workers]

    lines += [
        "",
        "---",
        "",
        f"*Generated by `agent_factory bootstrap` for org **{org.name}**.*",
        "",
    ]
    return "\n".join(lines)


def render_goals(org: Org, quarterly: list[str]) -> str:
    """Return the goals document every agent is expected to act against."""
    lines = [
        f"# Goals — {org.name}",
        "",
        f"**Founder:** {org.founder or '—'}",
        f"**Human team size:** {org.human_team_size}",
        "",
        "## North star",
        org.north_star.strip(),
        "",
        "## This quarter's targets",
    ]
    if quarterly:
        for i, g in enumerate(quarterly, 1):
            lines.append(f"{i}. {g.strip()}")
    else:
        lines.append("- (define targets during the next goal review)")
    lines += [
        "",
        "## Operating notes",
        "- Goals are reviewed quarterly; agent proactivity is expected to stay within "
        "its role's proactivity level while pursuing these.",
        "- Anything not codified in docs, email, or meetings should be captured (diary/"
        "context flow) so the company stays queryable.",
        "",
    ]
    return "\n".join(lines)


def render_org_readme(org: Org) -> str:
    """Summary of the generated org for humans browsing the folder."""
    lead = next((r for r in org.roles if r.reports_to is None), None)
    lines = [
        f"# {org.name} — AI workforce",
        "",
        f"**Founder:** {org.founder or '—'}  ",
        f"**North star:** {org.north_star}",
        "",
        "## Top of the org",
    ]
    if lead is not None:
        lines.append(f"- `{lead.id}` — {lead.title} (proactivity {lead.proactivity_level})")
    lines += ["", "## Roles", ""]
    for r in org.roles:
        lines.append(f"- `{r.id}` — {r.title}" + (f" → reports to `{r.reports_to}`" if r.reports_to else " (lead)"))
    lines += [
        "",
        "## Files",
        "- `roles/*.yaml` — machine-readable role definitions",
        "- `sops/*.md` — expected work procedures per role",
        "- `goals/current.md` — north star + quarterly targets",
        "- `settings.yaml` — org-level settings",
        "",
        "Validate this org with: `agent_factory validate --root .`",
        "",
    ]
    return "\n".join(lines)


def _proactivity_desc(level: int) -> str:
    table = {
        0: "Only does what it is directly told.",
        1: "Completes assigned tasks as specified.",
        2: "Finishes assigned tasks and surfaces follow-ups.",
        3: "Proposes new tasks; is goals-aware.",
        4: "Initiates new high-value work and reports tradeoffs.",
        5: "Self-directs new work and reports rollback + next steps.",
    }
    return table.get(level, "Unspecified.")
